# Generated by Django 5.1.2 on 2024-10-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
