# Generated by Django 5.1.2 on 2024-10-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='comment_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='comment_uz',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='username',
            field=models.CharField(max_length=10, verbose_name='Username'),
        ),
    ]
