# Generated by Django 5.1.2 on 2024-10-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_studentmodel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='is_active',
        ),
    ]
